name: Fourth Workflow
on: 
  workflow_run:
    workflows: ["Third Workflow"]
    types:
      - completed

jobs:
  greeting-command:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting
        run: echo "Hello" 
