name: Fourth Workflow
on: 
  workflow_run:
    workflows: ["Third Workflow"]
    types:
      - completed

jobs:
  success-command:
    runs-on: ubuntu-latest
    if: ${{github.event.workflow_run.conclusion == 'success'  }}
    steps:
      - name: Success greeting
        run: echo "Successfully executed the fourth workflow." 
  failure-command:
    runs-on: ubuntu-latest
    if: ${{github.event.workflow_run.conclusion == 'failure'}}
    steps:
      - name: Failure greeting
        run: echo "Failed to execute the fourth workflow."